### PR TITLE
Iso management

### PR DESCRIPTION
**Pull request by MatthewJohn**
Created Iso class to manage ISOs and implement passing of Iso objects when attatching ISOs to VMs

### CODE REVIEW

**Comment by MatthewJohn** [comment]
Have created #86

**Comment by MatthewJohn** [comment]
Implements #51 and succeeds #81

**Comment by sjs-itdev** [comment]
Reviewed, Looks good to me.

**Comment by itdevreviewboard** [comment]
**Build Log**
*last 5 lines*

 ```
[...truncated 15 lines...]
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Archiving artifacts
Recording fingerprints
Setting status of 6ab7b9a5cbab5b5d18ae675b18d9d06f39cd3090 to FAILURE with url http://mcvirt-jenkins.itdev.co.uk:8080/job/MCVirt_Github_PullRequests/112/ and message: 'Build finished. No test results found.'
```

**Pull request merged**
